### ISSUE TITLE
老哥 执行任务后报错

### ISSUE THREAD

**Issue by wyap-echo** [leaplu/DailyCP#1]
账号我填的是学号 这个有影响吗 
Traceback (most recent call last):
  File "/home/runner/.local/lib/python3.6/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/runner/.local/lib/python3.6/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/runner/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/home/runner/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "/home/runner/.local/lib/python3.6/site-packages/urllib3/connection.py", line 308, in connect
    conn = self._new_conn()
  File "/home/runner/.local/lib/python3.6/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7feef977f780>: Failed to establish a new connection: [Errno -2] Name or service not known

**Comment by UzkiS** [comment]
Name or service not known，不是账号的问题，你先检查学校前缀输入是否正确，你可以直接访问 https://学校前缀.campusphere.net/portal/login 看看是否能打开。如果在学校网址前缀没有输入错误的情况下，那可能是登陆方式的问题了，你可以试试原作者的新版能否正常登陆 https://gitee.com/Finch1/FuckDailyCP
